# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0002_auto_20170126_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
