# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0005_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
