# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0007_auto_20170202_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=None),
        ),
    ]
