# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0009_auto_20170202_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poked',
            field=models.ManyToManyField(to='LogReg.User'),
        ),
    ]
