# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0011_auto_20170203_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poked',
            field=models.ManyToManyField(blank=True, related_name='poked_by', to='LogReg.User'),
        ),
    ]
