# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0012_auto_20170203_0244'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='favorite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_key', to='exam.Quotes'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='favorited_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_key', to='LogReg.User'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LogReg.User'),
        ),
    ]
