# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170203_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='exam.Quotes'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='favorited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='LogReg.User'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogReg.User'),
        ),
    ]
